// Run with: node scripts/export.mjs
// Exports all Supabase data to scripts/backup.sql for import into Neon

import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'fs'

const supabase = createClient(
  'https://fhvxxidnztmsztexzjpi.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodnh4aWRuenRtc3p0ZXh6anBpIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MDM3NTY2OSwiZXhwIjoyMDk1OTUxNjY5fQ.AE7LTghRgqSpD6vpTj6XyrizqUAaNlQSXEN3AyVTOJ8'
)

function esc(v) {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'boolean') return v ? 'TRUE' : 'FALSE'
  if (typeof v === 'number') return String(v)
  if (Array.isArray(v)) {
    if (v.length === 0) return "ARRAY[]::text[]"
    return `ARRAY[${v.map(s => `'${String(s).replace(/'/g, "''")}'`).join(', ')}]`
  }
  return `'${String(v).replace(/'/g, "''")}'`
}

async function fetchAll(table, select = '*') {
  const { data, error } = await supabase.from(table).select(select).order('created_at', { ascending: true })
  if (error) throw new Error(`${table}: ${error.message}`)
  return data ?? []
}

const restaurants   = await fetchAll('restaurants')
const visits        = await fetchAll('restaurant_visits')
const notes         = await fetchAll('restaurant_notes')
const visitRatings  = await fetchAll('visit_ratings')

console.log(`restaurants:   ${restaurants.length}`)
console.log(`visits:        ${visits.length}`)
console.log(`notes:         ${notes.length}`)
console.log(`visit_ratings: ${visitRatings.length}`)

const lines = [
  '-- eat-list backup generated by scripts/export.mjs',
  '-- Import into Neon after running scripts/schema.sql',
  '',
]

if (restaurants.length) {
  lines.push('-- restaurants')
  for (const r of restaurants) {
    lines.push(
      `INSERT INTO restaurants (id,name,cuisine,address,suburb,city,state,notes,status,visit_count,first_visit_date,last_visit_date,would_go_again,tier,rating,price_level,website,instagram,tags,latitude,longitude,created_at,updated_at) VALUES (` +
      [r.id,r.name,r.cuisine,r.address,r.suburb,r.city,r.state,r.notes,r.status,r.visit_count,r.first_visit_date,r.last_visit_date,r.would_go_again,r.tier,r.rating,r.price_level,r.website,r.instagram,r.tags,r.latitude,r.longitude,r.created_at,r.updated_at].map(esc).join(',') +
      `) ON CONFLICT (id) DO NOTHING;`
    )
  }
  lines.push('')
}

if (visits.length) {
  lines.push('-- restaurant_visits')
  for (const v of visits) {
    lines.push(
      `INSERT INTO restaurant_visits (id,restaurant_id,visited_at,notes,rating,cost,created_at) VALUES (` +
      [v.id,v.restaurant_id,v.visited_at,v.notes,v.rating,v.cost,v.created_at].map(esc).join(',') +
      `) ON CONFLICT (id) DO NOTHING;`
    )
  }
  lines.push('')
}

if (notes.length) {
  lines.push('-- restaurant_notes')
  for (const n of notes) {
    lines.push(
      `INSERT INTO restaurant_notes (id,restaurant_id,content,created_at) VALUES (` +
      [n.id,n.restaurant_id,n.content,n.created_at].map(esc).join(',') +
      `) ON CONFLICT (id) DO NOTHING;`
    )
  }
  lines.push('')
}

writeFileSync('scripts/backup.sql', lines.join('\n'), 'utf8')
console.log('\nWrote scripts/backup.sql')
